### ISSUE TITLE
Add --color (opposite of --bw)

### ISSUE THREAD

**Issue by knghtbrd** [k4rtik/pydf#6]
Right now, --bw exists to temporarily omit color from output.  I'd like to see that supported in the config file as a default, and --color added as a command line argument to reverse it.

Using terminfo to detect when to use color or not would also be useful, but it's a bigger patch and I'm not prepared to write it just now.  ;)  Please let me know if a patch for the above would be wanted.

**Comment by knghtbrd** [comment]
Actually, I think I would be willing to make a patch also handle looking up colors codes for a given terminal, if they exist.  Seems that you can do this using curses.tigetstr and curses.tparm.  If you can't import those from curses you could simply force no color.

**Comment by k4rtik** [comment]
Same as my comments at #5
